export const guestMap: Record<string, string> = {
  "ban-giang": "Bạn Giang",
  "ban-toan": "Bạn Toàn",
  "ban-du": "Bạn Du",
  "ban-hien": "Bạn Hiến",
  "ban-trung": "Bạn Trung",
  "ban-hieu": "Bạn Hiếu",
  "ban-tu-trinh": "Bạn Tú Trinh",
  "ban-nhu-quynh": "Bạn Như Quỳnh",
  "ban-ngoc-thao": "Bạn Ngọc Thảo",
  "ban-truc-sang": "Bạn Trúc Sang",
  "ban-quang-binh": "Bạn Quang Bình",
  "ban-son-dinh": "Bạn Sơn Đinh",
  "ban-son-pham": "Bạn Sơn Phạm",
  "ban-ha-noi": "Bạn Hà Nội",
  "gd-ban-danh": "GĐ bạn Danh",
  "gd-ban-ha": "GĐ bạn Hà",
  "gd-ban-tram": "GĐ bạn Trâm",
  "gd-ban-phuong": "GĐ bạn Phương",
  "gd-ban-kim-phuong": "GĐ bạn Kim Phương",
  "gd-ban-thien-nhi": "GĐ bạn Thiên Nhi",
  "gd-ban-thuy": "GĐ bạn Thúy",
  "gd-ban-hang": "GĐ bạn Hằng",
  "gd-chi-yen": "GĐ Chị Yến",
  "ban-xuan-phong": "Bạn Xuân Phong",
  "ban-ngoc": "Bạn Ngọc",
  "ban-van": "Bạn Văn",
  "ban-long": "Bạn Long",
  "ban-tam": "Bạn Tâm",
  "ban-kieu-trang": "Bạn Kiều Trang",
  "ban-quang": "Bạn Quang",
  "anh-chi-hung-trinh": "Anh chị Hùng - Trinh",
  "em-quyen-unl": "Em Quyên UNL",
  "em-hong-unl": "Em Hồng UNL",
  "ban-chau-unl": "Bạn Châu UNL",
  "em-toan-unl": "Em Toàn UNL",
  "be-hien-dtl": "Bé Hiền DTL",
  "be-trinh-dtl": "Bé Trinh DTL",
  "em-vy-dtl": "Em Vy DTL",
  "em-nhu-y-dtl": "Em Như Ý DTL",
  "chi-duyen-dtl": "Chị Duyên DTL",
  "em-quynh-trang-dtl": "Em Quỳnh Trang DTL",
  "em-ngan-dtl": "Em Ngân DTL",
  "chi-ngan-ha-dtl": "Chị Ngân Hà DTL",
  "em-nam-dtl": "Em Nam DTL",
  "em-bich-tram-dtl": "Em Bích Trâm DTL",
  "em-thinh-dtl": "Em Thịnh DTL",
  "em-duy-dtl": "Em Duy DTL",
  "em-thu-ha-dtl": "Em Thu Hà DTL",
  "em-chi-dtl": "Em Chi DTL",
  "yen-nhi-dtl": "Yến Nhi DTL",
  "em-ai-xuan-dtl": "Em Ái Xuân DTL",
  "anh-hoang-dtl": "Anh Hoàng DTL",
  "chi-hue": "Chị Huệ",
  "em-ngoc-nhiem": "Em Ngọc Nhiệm",
  "chi-ngoc-ngan": "Chị Ngọc Ngân",
  "gd-ban-mai-thi": "GĐ Bạn Mai Thi",
  "ban-thao": "Bạn Thảo",
  "ban-kieu-dinh": "Bạn Kiều Đinh",
  "ban-ngoc-linh-nv": "Bạn Ngọc Linh NV",
  "ban-uyen-nv": "Bạn Uyên NV",
  "em-thuy-nv": "Em Thủy NV",
  "anh-vinh-chi-dieu": "Anh Vĩnh - Chị Diệu",
  "co-mung": "Cô Mừng",
  "co-nga": "Cô Nga",
};
